function cellInfo = test(varargin) 
% TEST returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'CommandBus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'velocity_command', 1, 'Bus: velocity_command', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'controlModePosVSOrient', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pos_ref', 3, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'takeoff_flag', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'orient_ref', 3, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'live_time_ticks', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Twist', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'linear', 1, 'Bus: linear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'angular', 1, 'Bus: angular', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'angular', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
    } ...
  } ...
  { ... 
    'linear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
  { ... 
    'velocity_command', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Twist', 1, 'Bus: Twist', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
